### ISSUE TITLE
Could you please upload example files (.pcd) required your process??

### ISSUE THREAD

**Issue by JunhaAgu** [ram-lab/lidar_appearance_calibration#1]
I'm asking because some pcd files don't seem to be in the data folder.

Thank you

**Comment by gogojjh** [comment]
> I'm asking because some pcd files don't seem to be in the data folder.
> 
> Thank you

Sure, I will do it asap!

**Comment by gogojjh** [comment]
Please check the folder: data/example/top_front/raw
Thanks.
