### ISSUE TITLE
Question about the part of initialization solution.

### ISSUE THREAD

**Issue by yulongshan** [ram-lab/lidar_appearance_calibration#2]
Firstly, thank you for your great work, it is really helpful for me. And  I want to ask you two problem about the part of B.
One is the equation(7):
![QQ截图20201122223451](https://user-images.githubusercontent.com/34642931/99906602-ff405700-2d12-11eb-82bd-2843a534c9a7.png)
I think O and O' is the coordinates in different coordinate system,(L1 and L2), so  equation 7 may be
t = O -RO'
The second question is why the elements of P ,Q matrix is ni - O,  and I think the normal vector has substract the origrin point.

**Comment by gogojjh** [comment]
Hi, thanks for your questions.
1. I have checked equ.(7) and agree with you for the first question. The equation should be t = O -RO'. 
2. Since we extract planes from the raw point cloud, n_i is represented in the {l_1} (the coordinate system). So n_i need to subtract O to transform itself into the ``wall'' coordinate system.
If you have any questions, please feel free to tell me ^v^.

**Comment by yulongshan** [comment]
Thank you for your relpying! I consider this question like this piture. 
![IMG_0083(20201125-192919)](https://user-images.githubusercontent.com/34642931/100222923-bf1ce680-2f55-11eb-8482-5f0b417016d4.PNG)
and the Q ,P is composed of n1,n2 n3 / n1' n2' n3' which do not include O/O'.

**If ni + O/- O, it will be one point, and we can get three matched points, then we can use ICP based on svd. Recalculating the Q and P matrix.**
 I think it's also right. Actually I find that it looks like this in your source code:
![QQ截图20201125194308](https://user-images.githubusercontent.com/34642931/100223524-93e6c700-2f56-11eb-946e-f29632f42714.png)

**Comment by gogojjh** [comment]
Sure, it is correct that this problem can be considered as an ICP. In the paper, we considered it as a problem of the axis alignment, so axes were subtracted by O.

**Comment by yulongshan** [comment]
Thanks for your replying again!
Maybe, there is one different view about it . Actually, I think that if we considered it as a problem of the axis alignment, we should not subtract by O or add on O. But if we treat it as ICP problem, we should add on O or subtracted by O. Because R ni = ni', Q and P should be composed of ni and ni'.
I think it is correct in the source code.
________________________________
